AWSTemplateFormatVersion: '2010-09-09'
Description: Stack to set up Apache on a Linux EC2 instance and allocate an Elastic IP address

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0abcdef1234567890
    us-west-2:
      AMI: ami-0604d81f2fd264c7b

Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
    ConstraintDescription: must be a valid EC2 instance type.

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

  VPCStackName:
    Description: Name of the stack that contains the VPC
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Enable SSH access"
      VpcId:
        Fn::ImportValue: !Sub '${VPCStackName}-VPCID'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 173.66.94.214/32
      Tags:
       - Key: "Name"
         Value: "SSH SG"

  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !FindInMap
        - RegionMap
        - !Ref "AWS::Region"
        - AMI
      KeyName: !Ref KeyName
      SubnetId: !ImportValue
        Fn::Sub: '${VPCStackName}-SubnetID'
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
        - Fn::ImportValue: !Sub '${VPCStackName}-SecurityGroupID'
      Tags:
       - Key: "Name"
         Value: "MyApacheWebserver"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          echo "<html><body><h1>This Server was launched by Annie using cloudformation template</h1></body></html>" > /var/www/html/index.html
          systemctl start httpd
          systemctl enable httpd

  EIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyEC2Instance

Outputs:
  InstancePrivateIP:
    Description: "Private IP address of the EC2 instance"
    Value: !GetAtt MyEC2Instance.PrivateIp
    Export:
      Name: !Sub '${AWS::StackName}-PrivIP'
  InstancePublicDNS:
    Description: "Public DNS name of the EC2 instance"
    Value: !GetAtt MyEC2Instance.PublicDnsName
    Export:
      Name: !Sub '${AWS::StackName}-pubDNSname'
